import { PricingPlan } from "../pricing-card"
import { categories } from "./categories"

type Category = (typeof categories)[number]

export const pricingData: Record<Category, PricingPlan[]> = {
    'Web Design': [
        {
            name: 'Starter Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 299,
            deleted_price: 600,
            discount: 50,
            features: [
                '5 Stock Photos',
                '5 Page Website',
                '3 Banner Design',
                '1 jQuery Slider Banner',
                'FREE Google Friendly Sitemap',
                'Complete W3C Certified HTML',
                '48 to 72 hours TAT',
                '100% Satisfaction Guarantee',
            ],
            popular: false,
        },
        {
            name: 'Professional Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 599,
            deleted_price: 1200,
            discount: 50,
            features: [
                '10 Unique Pages Website',
                'CMS / Admin Panel Support',
                '8 Stock images',
                '5 Banner Designs',
                '1 jQuery Slider Banner',
                'FREE Google Friendly Sitemap',
                'Complete W3C Certified HTML',
                '48 to 72 hours TAT',
                'Complete Deployment',
                '100% Satisfaction Guarantee',
                '100% Unique Design Guarantee',
                '100% Money Back Guarantee *',
                'Mobile Responsive will be Additional $99*',
            ],
            popular: true,
        },
        {
            name: 'Elite Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 999,
            deleted_price: 2000,
            discount: 50,
            features: [
                'Upto 15 Unique Pages Website',
                'Conceptual and Dynamic Website',
                'Mobile Responsive',
                'Online Reservation/Appointment Tool (Optional)',
                'Online Payment Integration (Optional)',
                'Custom Forms',
                'Lead Capturing Forms (Optional)',
                'Striking Hover Effects',
                'Newsletter Subscription (Optional)',
                'Newsfeed Integration',
                'Social Media Integration',
                'Search Engine Submission',
                '5 Stock Photos',
                '3 Unique Banner Design',
                '1 jQuery Slider Banner',
                'Complete W3C Certified HTML',
                '48 to 72 hours TAT',
                'Facebook Page Design',
                'Twitter Page Design',
                'YouTube Page Design',
                'Complete Deployment',
                '100% Satisfaction Guarantee',
                '100% Unique Design Guarantee',
                '100% Money Back Guarantee *',
                'Buy Now',
                'Live Chat',
            ],
            popular: false,
        },
        {
            name: 'Custom Wordpress Website',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 1599,
            deleted_price: 3200,
            discount: 50,
            features: [
                '15 to 20 Pages Website',
                'Custom Made, Interactive, Dynamic & High End Design',
                'Custom WP',
                '1 jQuery Slider Banner',
                'Up to 10 Custom Made Banner Designs',
                '10 Stock Images',
                'Unlimited Revisions',
                'Special Hoover Effects',
                'Content Management System (CMS)',
                'Online Appointment/Scheduling/Online Ordering Integration (Optional)',
                'Online Payment Integration (Optional)',
                'Multi Lingual (Optional)',
                'Custom Dynamic Forms (Optional)',
                'Signup Area (For Newsletters, Offers etc.)',
                'Search Bar',
                'Live Feeds of Social Networks integration (Optional)',
                'Mobile Responsive',
                'FREE 5 Years Domain Name',
                'Free Google Friendly Sitemap',
                'Search Engine Submission',
                'Complete W3C Certified HTML',
                'Industry Specified Team of Expert Designers and Developers',
                'Complete Deployment',
                'Dedicated Accounts Manager',
                'Facebook Page Design',
                'Twitter Page Design',
                'YouTube Page Design',
                '100% Ownership Rights',
                '100% Satisfaction Guarantee',
                '100% Unique Design Guarantee',
                '100% Money Back Guarantee *',
            ],
            popular: false,
        },
        {
            name: 'Custom PHP Website',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 2499,
            deleted_price: 5000,
            discount: 50,
            features: [
                '15 to 20 Pages Website',
                'Custom Made, Interactive, Dynamic & High End Design',
                'Custom WP/PHP',
                '1 jQuery Slider Banner',
                'Up to 10 Custom Made Banner Designs',
                '10 Stock Images',
                'Unlimited Revisions',
                'Special Hoover Effects',
                'Content Management System (CMS)',
                'Online Appointment/Scheduling/Online Ordering Integration (Optional)',
                'Online Payment Integration (Optional)',
                'Multi Lingual (Optional)',
                'Custom Dynamic Forms (Optional)',
                'Signup Area (For Newsletters, Offers etc.)',
                'Search Bar',
                'Live Feeds of Social Networks integration (Optional)',
                'Mobile Responsive',
                '15 Seconds 2D Explainer Video',
                'Voice - Over & Sound Effects',
                'Professional Script Writing',
                'Storyboard',
                'SEO Meta Tags',
                'FREE 5 Years Domain Name',
                'Free Google Friendly Sitemap',
                'Search Engine Submission',
                'Complete W3C Certified HTML',
                'Industry Specified Team of Expert Designers and Developers',
                'Complete Deployment',
                'Dedicated Accounts Manager',
                '100% Ownership Rights',
                '100% Satisfaction Guarantee',
                '100% Unique Design Guarantee',
                '100% Money Back Guarantee *',
            ],
            popular: false,
        },
        {
            name: 'Automated Portal Website',
            tagline: 'Suitable for potential Mid Sized and Enterprise companies.',
            price: 4999,
            deleted_price: 10000,
            discount: 50,
            features: [
                'Unlimited Page Website',
                'Custom Content Management System (CMS)',
                'Unique Pages and UI Design',
                'Complete Custom Development',
                'Process Automation Tools',
                'Newsfeed Integration',
                'Social Media Plugins Integration',
                'Up to 40 Stock images',
                '10 Unique Banner Designs',
                'JQuery Slider',
                'Search Engine Submission',
                'Free Google Friendly Sitemap',
                'Custom Email Addresses',
                'Social Media Page Designs (Facebook, Twitter, Instagram)',
                'Complete W3C Certified HTML',
                'Complete Deployment',
                '100% Satisfaction Guarantee',
                '100% Unique Design Guarantee',
                'Money Back Guarantee',
                'Automated Course Creation',
                'Video Conferencing',
                'Skills/Certification Tracking',
                'Mobile Learning',
                'Asynchronous Learning',
                'CRM Features',
                'Gamification',
                'Social Learning/Message Boards',
                'Motivational Triggers',
                'Forums And Webinars',
                'E-commerce And Subscriptions',
                'Online Course Booking',
                'Excellent Reporting',
                'Invoicing Integration',
                'Financial Integrations',
                'Student Information management',
                'Automated communications',
                'Learning Management System',
                'Quick And Easy Course Scheduling',
                'Reporting And Data Analysis',
                'Assessment Management & Live Feedback',
                'Gradebooks',
                'Quick User Integration',
                'Easy Payment Methods',
                'Online Communities & Social Engagement',
                'Curation of Resources And Adding Own Resources',
            ],
            popular: false,
        },
    ],
    'Logo Design': [
        {
            name: 'Startup logo',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 49,
            deleted_price: 120,
            discount: 59,
            features: [
                '5 Custom Logo Design Concepts By 2 Designers',
                'UNLIMITED Revisions',
                '48 to 72 hours TAT',
                'Rush Delivery Available',
                '100% Satisfaction Guarantee',
                '100% Unique Design Guarantee',
                '100% Money Back Guarantee *',
            ],
            popular: false,
        },
        {
            name: 'Professional logo',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 120,
            deleted_price: 240,
            discount: 50,
            features: [
                'Unlimited Logo Design Concepts',
                '4 Dedicated Designers',
                'UNLIMITED Revisions',
                'FREE Business Card Design',
                'FREE Letterhead Design',
                'FREE Envelope Design',
                'Vector Formats (PSD, EPS, PNG, GIF, JPG, PDF)',
                'Rush Delivery Available',
                '100% Satisfaction Guarantee',
                '100% Unique Design Guarantee',
                '100% Money Back Guarantee *',
            ],
            popular: true,
        },
        {
            name: 'Business logo',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 250,
            deleted_price: 500,
            discount: 50,
            features: [
                'UNLIMITED Logo Design Concepts',
                'By 8 Award Winning Designers',
                'UNLIMITED Revisions',
                '2 Stationary Design Sets (Business Card, Letterhead, Envelope)',
                'FREE Icon Design',
                'FREE MS Word Letterhead',
                'FREE Email Signature',
                'All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)',
                '100% Ownership Rights',
                '100% Satisfaction Guarantee',
                '100% Unique Design Guarantee',
                '100% Money Back Guarantee *',
            ],
            popular: false,
        },
    ],
    'eCommerce': [
        {
            name: 'Beginners E-Commerce Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 999,
            deleted_price: 1999,
            discount: 50,
            features: [
                'Upto 15 Unique Pages Website',
                'Conceptual and Dynamic Website',
                'Content Management System (CMS)',
                'Mobile Responsive',
                'Easy Product Search',
                'Product Reviews',
                'Up To 100 Products',
                'Up To 7 Categories',
                'Full Shopping Cart Integration',
                'Payment Module Integration',
                'Sales & Inventory Management',
                'Jquery Slider',
                'Free Google Friendly Sitemap',
                'FREE 1 Years Hosting',
                'Custom Email Addresses',
                'Complete W3C Certified HTML',
                'Facebook Page Design',
                'Twitter Page Design',
                'Youtube Channel Setup',
                'Complete Deployment',
                'Dedicated Accounts Manager',
                '100% Ownership Rights',
                '100% Satisfaction Guarantee',
                '100% Unique Design Guarantee',
                '100% Money Back Guarantee *',
            ],
            popular: false,
        },
        {
            name: 'Corporate E-Commerce Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 1799,
            deleted_price: 3599,
            discount: 50,
            features: [
                'Unlimited Unique Pages Website',
                'Conceptual and Dynamic Website',
                'Content Management System (CMS)',
                'Mobile Responsive',
                'Easy Product Search',
                'Product Reviews',
                'Unlimited Products',
                'Unlimited Categories',
                'Full Shopping Cart Integration',
                'Payment Module Integration',
                'Sales & Inventory Management',
                'Jquery Slider',
                'Free Google Friendly Sitemap',
                'FREE 3 Years Hosting',
                'Custom Email Addresses',
                'Complete W3C Certified HTML',
                'Facebook Page Design',
                'Twitter Page Design',
                'Youtube Channel Setup',
                'Instagram Page Design',
                'Complete Deployment',
                'Dedicated Accounts Manager',
                '100% Ownership Rights',
                '100% Satisfaction Guarantee',
                '100% Unique Design Guarantee',
                '100% Money Back Guarantee',
            ],
            popular: true,
        },
        {
            name: 'Automated / Interactive E-Commerce Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 9999,
            deleted_price: 19998,
            discount: 50,
            features: [
                'Unlimited Page Website',
                'Custom Content Management System (CMS)',
                'Unique Pages and UI Design',
                'Complete Custom Development',
                'Process Automation Tools',
                'Newsfeed Integration',
                'Social Media Plugins Integration',
                'Upto 40 Stock images',
                '10 Unique Banner Designs',
                'JQuery Slider',
                'Search Engine Submission',
                'Free Google Friendly Sitemap',
                'FREE 5 Years Hosting',
                'Custom Email Addresses',
                'Social Media Page Designs (Facebook, Twitter, Instagram)',
                'Complete W3C Certified HTML',
                'Complete Deployment',
                '100% Satisfaction Guarantee',
                '100% Unique Design Guarantee',
                'Money Back Guarantee',
                'Automated Inventory/Shipping/Supplier Module:',
                'Manage thousands to millions of inventory with ease and check stock levels in real-time. Receive low inventory notifications and generate purchase orders to replenish your stock.',
                'Suppliers Integration (API NEEDED)',
                'Shipper Integration (API NEEDED)',
                'Order management',
                'LOT numbers and expire date tracking',
                'Transfer stock between warehouses (If Warehouse - API NEEDED)',
                'Receive stock into a specific warehouse (If Warehouse - API NEEDED)',
                'Fulfill orders from a particular warehouse (If Warehouse - API NEEDED)',
                'Stock Management',
                'Actionable Insights',
                'Real- Time Visibility Inventory Opportunities',
                'Advanced Supplier Communication (API Required)',
                'Speak to suppliers during trivial conversations',
                'Send governance and compliance actions to suppliers',
                'Place purchasing requests',
                'Research and answer procurement-related queries',
                'Research supplier and supplier-set information',
                'Invoice receiving and filing',
                'Payment documentation management',
                'Order request documentation',
                'Machine Learning (ML) for Supply Chain Planning (SCP)',
                'Machine Learning (ML) for Warehouse Management',
                'Natural Language Processing (NLP) for Data Cleansing',
                'Data Robustness Enhancement using NLP',
                'Automated Invoices & Estimates',
                'Generate professional invoices and estimates',
                'Instant PDF invoice generation',
                'Email invoices and estimates directly to customers',
                'Automated Split Invoicing',
                'Automated Combined Invoicing',
                'Invoice Templates',
                'Automated Barcode Scanning',
                'Scan inventory into orders',
                'Generate barcodes for inventory and documents',
                'Search inventory using barcode scanning',
                'Search documents using barcode scanning',
                'Multi-Warehouse Locations & Zones',
                'Support for multiple warehouses, offices, and retail stores',
                'Track inventory across locations and zones',
                'Custom inventory attributes (size, color, location)',
                'Global inventory visibility',
                'Location-wise inventory visibility',
                'Customer Accounts Management',
                'Performance Analytics',
                'Business Analytics',
                'Personal Details Customization',
                'Process Management',
                'Sales Automation',
                'Team Collaboration',
                'Marketing Automation',
                'Advanced Security',
                'Third-Party Integrations',
                'Mobile Notifications',
                'Sales Reports',
                'Trend Analytics',
                'Sales Forecasting',
                'Territory Management',
                'Account Management',
                'Event Integration',
                'Advanced Data Security',
                'Integrated Purchase Orders',
                'Inventory Replenishment',
                'Purchase Order Tracking',
                'Incoming Stock Tracking',
                'Partial Order Fulfillment',
                'Backorder Management',
                'Financial Reports',
                'Detailed Inventory Reports',
                'Detailed Sales Reports',
                'Detailed Service Reports',
                'Date Range Report Filtering',
                'Category-wise Report Filtering',
                'Profitability Analysis'
            ],
            popular: false,
        },
        {
            name: 'Custom E Commerce Marketplace Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 6999,
            deleted_price: 14000,
            discount: 50,
            features: [
                'Unlimited Page Website',
                'Unique Pages and UI Design',
                'Complete Custom Development',
                'Newsfeed Integration',
                'Social Media Plugins Integration',
                'Advanced Ecommerce Marketplace Features',
                'Inventory Management',
                'CRM (Customer Relationship Management System)',
                'Advanced Admin Features 2.0',
                'Advanced User Features',
                'Dashboard and Analytics',
                'Seller & Shipping Distribution',
                'Seller Profile Management',
                'User Profile Management',
                'General Configuration Features',
                'Revenue Models',
                'Featured Products Module',
                'Google Advertisements Integration',
                'Flash Sales Module',
                'Loyalty Rewards Module',
                'Up to 40 Stock Images',
                '10 Unique Banner Designs',
                'jQuery Slider',
                'Search Engine Submission',
                'Free Google-Friendly Sitemap',
                'Social Media Page Designs (Facebook, Twitter, Instagram)',
                'Complete W3C Certified HTML',
                'Complete Deployment',
                '100% Satisfaction Guarantee',
                '100% Unique Design Guarantee',
                'Money Back Guarantee'
            ],
            popular: false,
        },
        {
            name: 'Custom CRM/ERP Portal Website Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 15000,
            deleted_price: 30000,
            discount: 50,
            features: [
                'Unlimited Page Website',
                'Unique Pages and UI Design',
                'Complete Custom Development',
                'Newsfeed Integration',
                'CRM (Customer Relationship Management System)',
                'Performance and Analytics',
                'Customization of Personal Details',
                'Process Management',
                'Sales Automation',
                'Team Collaboration',
                'Marketing Automation',
                'Security Integrations',
                'Mobile Notifications',
                'Sales Reports',
                'Trend Analytics',
                'Forecasting',
                'Territory Management',
                'Account Management',
                'Event Integration',
                'Advanced Data Security',
                'Opportunity Management',
                'Sales Forecasting',
                'Call & Video Logging',
                'Quotes Management',
                'Contracts Management',
                'Document Library',
                'Case Management',
                'Analytics & Dashboards',
                'Lead Management',
                'Resource Management',
                'Web Intelligence',
                'Automated Emails',
                'Automated Invoices & Estimates',
                'Automated Split Invoicing',
                'Automated Combined Invoicing',
                'Invoice Templates',
                'Financial Reports',
                'Detailed Sales Reports',
                'Detailed Service Reports',
                'Date Range Report Filtering',
                'Category-wise Report Filtering',
                'Profitability Analysis',
                'Automated Sales Reports',
                'Core ERP Modules',
                'Human Resources Integration',
                'Business Intelligence',
                'Sales & Marketing Management',
                'Finance Management',
                'Core ERP Features',
                'Advanced Reporting',
                'Accounting',
                'Tracking & Visibility',
                'Centralized Modules',
                'ERP Database',
                'Human Resources Management',
                'Business Process Management',
                'Enterprise Analytics',
                'ERP Integrations',
                'Manufacturing Integration (Optional)',
                'Distribution Management',
                'Business Intelligence Insights',
                'Business Standardization',
                'Procurement Management',
                'Reporting & Analytics',
                'Forecasting & Projections',
                'Enterprise-wide Integration',
                'Real-Time Operations',
                'Problem Definition',
                'Program Objectives & Scope Documentation',
                'Implementation Assumptions',
                'Implementation Cost Planning',
                'Implementation Scheduling',
                'Development & Operational Risk Assessment',
                'Projected Benefits Analysis',
                'Team Member Management',
                'Contracts Management',
                'Infrastructure Upgrades',
                'Work Plan & Timeline Creation',
                'Gap Analysis',
                'System Configuration',
                'Data Migration',
                'System Testing',
                'System Documentation',
                'Advanced Admin Features 2.0',
                'User Signup & Login Functionality',
                'Advanced User Features',
                'User Profile Management',
                'General Configuration Features',
                'Complete W3C Certified HTML',
                'Complete Deployment',
                '100% Satisfaction Guarantee',
                '100% Unique Design Guarantee',
                'Money Back Guarantee'
            ],
            popular: false,
        },
    ],
    'Social Media Marketing': [
        {
            name: 'Silver Marketing Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 499,
            deleted_price: 699,
            discount: 29,
            features: [
                '2 Social Media Channels (Facebook / Instagram)',
                '3 postings per week (per network)',
                '1 Cover Picture Social Account Setup',
                'Business Page Optimization',
                'Social Media Strategy',
                'Content Creation',
                'Increase in followers',
                'Account Management',
                'Monthly Progress report',
                'No Setup Fee',
                'Cancel any time',
            ],
            popular: false,
        },
        {
            name: 'Gold Marketing Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 999,
            deleted_price: 1500,
            discount: 33,
            features: [
                'Social media account setup',
                'Complete account management',
                '5 posts per week (per network)',
                'Custom editorial calendar (review before publishing)',
                'Dedicated account manager',
                'Dedicated budget for paid advertising',
            ],
            popular: true,
        },
        {
            name: 'Platimum Marketing Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 2500,
            deleted_price: 3500,
            discount: 29,
            features: [
                '4 Social Media Channels (Facebook / Twitter / Pinterest / Instagram)',
                'Social media account setup',
                'Complete account management',
                '6 posts per week (per network)',
                'Custom editorial calendar (review before publishing)',
                'Call to Action Integration',
                'End of Term Report',
                'Dedicated Account Manager',
                'Dedicated Budget for Paid Advertising',
            ],
            popular: false,
        },
    ],
    'SEO': [
        {
            name: 'Startup SEO Packages',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 449,
            deleted_price: 898,
            discount: 50,
            features: [
                '5 Keywords Guaranteed Google Ranking',
                'Off-site SEO Optimization',
                'Link Building',
                'Social Bookmarking',
                'Basic Analytics Report',
                'In-depth Website Analysis',
                'Content Duplicate Check',
                'Initial Backlink Analysis',
                'Google Penalty Check',
                'Mobile Usability Check',
                'Competitor Analysis',
                'Keyword Research',
                'Informational Content Writing (2 per Month)',
                'Content Distribution & Sharing (2 per Month)',
                'Blog Writing (1 per Month)',
                'Press Release Creation',
                'Social Bookmarking (5 per Month)',
                'NAP Syndication',
                'Google My Business Optimization',
                'Bing Local Listing Optimization',
                'Citation Building',
                'Classified Ad Submissions',
                'Google Analytics Setup & Analysis',
                'SEO Performance Reports',
                'Search Engine Ranking Reports',
                'Dedicated Account Manager',
                'Monthly SEO Action Plan',
                'Monthly Activity Report'
            ],
            popular: false,
        },
        {
            name: 'Identity SEO Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 849,
            deleted_price: 1698,
            discount: 50,
            features: [
                '10 Keywords',
                'Guaranteed Google Ranking',
                'Off-site SEO Optimization',
                'On-site SEO Optimization',
                'Link Building',
                'Social Bookmarking',
                'In-depth Website Analysis',
                'Content Duplicate Check',
                'Initial Backlink Analysis',
                'Google Penalty Check',
                'Mobile Usability Check',
                'Competitor Analysis',
                'Keyword Research',
                'Title & Meta Tags Optimization',
                'Content Optimization',
                'Page Speed Analysis',
                'Page Speed Optimization',
                'HTML Code Cleanup & Optimization',
                'Internal Link Structure Optimization',
                'Page Heading (H1-H6) Optimization',
                'Canonicalization',
                '301 Redirect Setup',
                'Website Page Load Optimization',
                'Schema Markup Implementation',
                'Image Optimization',
                'Hyperlink Optimization',
                'Robots.txt Creation & Analysis',
                'Blog Writing (2 per Month)',
                'Informational Content Writing (1 per Month)',
                'Content Distribution & Sharing',
                'Press Release Writing',
                'Press Release Distribution',
                'Social Bookmarking for Press Releases',
                'Google Search Console Setup',
                'Google Analytics Setup & Integration'
            ],
            popular: true,
        },
        {
            name: 'Elite SEO Packages',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 1549,
            deleted_price: 3098,
            discount: 50,
            features: [
                '20 Keywords',
                'Guaranteed Google Ranking',
                'Off-site SEO Optimization',
                'On-site SEO Optimization',
                'Link Building',
                'Social Bookmarking',
                'In-depth Website Analysis',
                'Content Duplicate Check',
                'Initial Backlink Analysis',
                'Google Penalty Check',
                'Mobile Usability Check',
                'Competitor Analysis',
                'Keyword Research',
                'Page Speed Analysis',
                'Page Speed Optimization',
                'Title & Meta Tags Optimization',
                'Content Optimization',
                'HTML Code Cleanup & Optimization',
                'Internal Link Structure Optimization',
                'Page Heading (H1-H6) Optimization',
                'Canonicalization',
                '301 Redirect Setup',
                'Website Page Load Optimization',
                'Robots.txt Creation & Analysis',
                'Press Release Writing',
                'Press Release Distribution',
                'Social Bookmarking for Press Releases',
                'Schema Markup Implementation',
                'Image Optimization',
                'Hyperlink Optimization',
                'Google Search Console Setup',
                'Google Analytics Setup & Integration',
                'Blog Writing (2 per Month)',
                'Informational Content Writing (1 per Month)',
                'Content Distribution & Sharing'
            ],
            popular: false,
        },
    ],
    'Video': [
        {
            name: 'Startup Video Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 499,
            deleted_price: 998,
            discount: 50,
            features: [
                '30 Seconds Duration Video',
                'Premium Script Writing',
                'Storyboard Design',
                'Hand-drawn Illustrations',
                'Animation Effects & Visualization',
                'Music & Foley Sound Design',
                'Professional Voice Over',
                'All Accent Voice Options',
                'Unlimited Revisions',
                '4 Weeks Delivery Time',
                'Sample Theme Concepts',
                'Dedicated Account Manager'
            ],
            popular: true,
        },
        {
            name: 'Platimum Video Package',
            tagline: 'Suitable for potential super-startups and brand revamps for companies',
            price: 1199,
            deleted_price: 2398,
            discount: 50,
            features: [
                '90 Seconds Duration HD 1080 Video',
                'Premium Script Writing',
                'Storyboard Design',
                'Hand-drawn Illustrations',
                'Animation Effects & Visualization',
                'Music & Foley Sound Design',
                'Professional Voice Over',
                'All Accent Voice Options',
                'Unlimited Revisions',
                '4 Weeks Delivery Time',
                'Sample Theme Concepts',
                'Dedicated Account Manager'
            ],
            popular: false,
        },
    ],
}